server:
  port: 8080
  servlet:
    context-path: /ccty

spring:
  application:
    name: ccty
  datasource:
    # 数据源
    url: jdbc:mysql://192.168.175.120:3306/e_commerce?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  type-aliases-package: com.ccty.entity
  global-config:
    db-config:
      id-type: auto
